language: python
dist: trusty
sudo: required

python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.6"

install:
  - make install

after_success:
  - coveralls

# command to run tests
script:
  - make test
