language: python
sudo: false

cache: pip

services:
  - docker

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - make pull

install:
  - make install

after_success:
  - coveralls

script:
  - make test
